name: CMake Build

on: [push]

jobs:
  build-and-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            os: windows-latest
          }
        - {
            name: "Ubuntu Latest",
            os: ubuntu-latest
          }
        - {
            name: "MacOS",
            os: macos-latest
          }

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.3
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON