name: CMake Build

on: [push]

jobs:
  build-and-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest",
            os: ubuntu-latest,
            gen: "Unix Makefiles",
            print: "cat"
          }
        - {
            name: "Windows Latest",
            os: windows-latest,
            gen: "MinGW Makefiles",
            print: "Get-Content -Path"
          }
        - {
            name: "macOS Latest Clang",
            os: macos-latest,
            gen: "Unix Makefiles",
            print: "cat"
          }
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: create build dir
      shell: cmake -P {0}
      run: |
        file(MAKE_DIRECTORY build)

    - name: build
      run: |
        cd build
        cmake -G "${{matrix.config.gen}}" .. 
        cmake --build .

    - name: print cmake error log
      if: ${{ always() }}
      run: |
        ${{matrix.config.print}} ./build/CMakeFiles/CMakeError.log
        #Get-Content -Path "D:/a/ddPCM/ddPCM/build/CMakeFiles/CMakeError.log"
        