name: Build MacOS

on: [push]

jobs:
  build:
    name: MacOS Build
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
        path: repo

    - name: create build dir
      shell: cmake -P {0}
      run: |
        file(MAKE_DIRECTORY repo/build)
    
    - name: build
      run: |
        cd repo/build
        cmake -G "Unix Makefiles" -DCMAKE_Fortran_COMPILER="gfortran-10" .. 
        cmake --build .

    - name: pack
      run: |
        tar -cf built_repo_mac.tar repo

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: built_repo_mac
        path: built_repo_mac.tar
        