name: CMake Build

on: [push]

jobs:
  build-and-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest",
            os: ubuntu-latest
          }
        - {
            name: "Windows Latest",
            os: windows-latest
          }

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: create build dir
      shell: cmake -P {0}
      run: |
        file(MAKE_DIRECTORY build)
    - name: check gfortran
      run: |
        gfortran
    - name: build
      if: runner.os == 'Windows'
      run: |
        cd build
        cmake -G "MinGW Makefiles" .. 
        cmake --build .

    - name: print cmake error log
      if: ${{ always() && runner.os == 'Windows'}}
      run: |
        Get-Content -Path "D:/a/ddPCM/ddPCM/build/CMakeFiles/CMakeError.log"
        