name: CMake Build

on: [push]

jobs:
  build-and-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest",
            os: ubuntu-latest
          }
        - {
            name: "Windows Latest",
            os: windows-latest
          }

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: download gfortran
      shell: cmake -P {0}
      run: |
        if ("${{ runner.os }}" STREQUAL "Windows")
          set(fortran_url "https://sourceforge.net/projects/mingw/files/MinGW/Base/gcc/Version6/gcc-6.3.0/gcc-fortran-6.3.0-1-mingw32-bin.tar.xz/download")
          file(DOWNLOAD "${fortran_url}" ./fortran/fortran.tar.xz SHOW_PROGRESS)
          execute_process(
            COMMAND ${CMAKE_COMMAND} -E tar xvf ./fortran.tar.xz
            WORKING_DIRECTORY ./fortran
          )
          set(ENV{FC} "$ENV{GITHUB_WORKSPACE}\\fortran\\bin\\gfortran.exe")
          set(CMAKE_FC_COMPILER  "$ENV{GITHUB_WORKSPACE}\\fortran\\bin\\gfortran.exe")
        endif()
    - name: check dirs
      if: runner.os == 'Windows'
      run: |
        echo 'test'
        cd fortran
        dir

    - name: build
      shell: cmake -P {0}
      run: |
        cmake . --build ./build