name: Build Ubuntu

on: [push]

jobs:
  build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
        path: repo

    - name: create build dir
      shell: cmake -P {0}
      run: |
        file(MAKE_DIRECTORY repo/build)
    
    - name: build
      run: |
        cd repo/build
        cmake -G "Unix Makefiles" -DCMAKE_Fortran_COMPILER="gfortran-10" .. 
        cmake --build .

    - name: pack
      run: |
        

    - name: Run tests
      shell: cmake -P {0}
      run: |
        include(ProcessorCount)
        ProcessorCount(N)
        execute_process(
          COMMAND ctest -j ${N}
          WORKING_DIRECTORY build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Running tests failed!")
        endif()
      
    
    - name: print cmake error log
      if: ${{ always() }}
      run: |
        cat ./repo/build/CMakeFiles/CMakeError.log
        