name: Test Ubuntu

on: [push]

jobs:
  test:
    name: Ubuntu Test
    runs-on: ubuntu-latest
    steps:
    - name: Download Build
      uses: benday-inc/download-latest-artifact@main
      with:
         workflow_name: 'Build Ubuntu'
         branch_name: 'ddX'
         download_path: '.'
         download_filename: 'art.zip'

    - name: check dir
      run: |
        ls
        