name: Test Mac

on: [push]

jobs:
  test:
    name: MacOS Test
    runs-on: macos-latest
    steps:
    - name: Download Build
      uses: benday-inc/download-latest-artifact@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository_owner: 'Nige91'
        repository_name: 'ddPCM'
        workflow_name: 'Build MacOS'
        branch_name: 'ddX'
        download_path: '.'
        download_filename: 'art.zip'

    - name: Unpack
      run: |
        tar -xzf art.zip
        tar -xzf built_repo_mac.tar

    - name: check dir
      run: |
        ls

    - name: Test
      run: |
        cd repo/build
        ctest

    
        